### ISSUE TITLE
48-7S "Spark" Liquid Fuel Engine - Emissive not displaying correctly

### ISSUE THREAD

**Issue by Poodmund** [PorktoberRevolution/ReStocked#290] opened 2019-02-03 15:11 UTC
After having looked at the texture assets, I think more of the part is supposed to be affected by the emissive texture. Currently, only the inside of the engine bell is ramping up to display the emissive overlay but I think part of the outside of the bell may supposed to have a slight glow also. See screenshots:

![untitled-1](https://user-images.githubusercontent.com/10106634/52178405-f7be5f80-27c5-11e9-9034-aefdeece284c.png)

![untitled-2](https://user-images.githubusercontent.com/10106634/52178407-fc831380-27c5-11e9-8089-9c43edc8b48d.png)

Please close if not the case.

**Comment by ChrisAdderley** [comment] 2019-02-04 17:33
Duplicate of https://github.com/PorktoberRevolution/ReStocked/issues/257

**Closed by ChrisAdderley** 2019-02-04 17:33 UTC
