### ISSUE TITLE
Colliders are slanted for no apparent reason

### ISSUE THREAD

**Issue by c-lipka** [PorktoberRevolution/ReStocked#862] opened 2020-05-26 10:23 UTC
The sides of some ReStock parts' colliders are slightly off-vertical for no good reason (and differing from stock), making surface-attached parts look wonky. This effect is also rather localized (i.e. doesn't happen along the entire length of the side), indicating that the collider geometry may be far more complex than necessary. Observed so far with the following parts:

- Okto probe core
- 1.25m Service Bay

For demonstration I've stuck solar panels to the offending parts, then duplicated them along with the attached panels. Note how the panels fail to align properly (as they would if they were attached vertically), and overlap shingle-style instead:

![screenshot3](https://user-images.githubusercontent.com/3574445/82888242-5f636580-9f49-11ea-8b9e-c41055023c25.jpg)
![screenshot4](https://user-images.githubusercontent.com/3574445/82888254-625e5600-9f49-11ea-8e10-acbedbc74664.jpg)

I have a hunch that some other parts' collider geometry may have similar issues (being out of whack and/or overly complex). I will keep my eyes peeled for surface attachment symptoms, but someone more skilled than me might want to do a more systematic review of the actual collider meshes.

**Comment by ChrisAdderley** [comment] 2020-05-27 17:40
These colliders are imported from the game and reexported, so they're not exactly overly complex or anything. That being said, something like this appeared on one or two parts before, so I'll look into it.

**Comment by ChrisAdderley** [comment] 2020-05-27 18:39
Note to future self: fbx imports of colliders show different normals on each triangular face even if they are coplanar. Need to apply a smoothing group at angle ~1 to clean these up before export.

Resolved in f5306eda9f3aaf26066c592b8f1c190c8afee7bd

**Comment by ChrisAdderley** [comment] 2020-05-29 20:43
Released with 1.1.2

**Comment by c-lipka** [comment] 2020-06-01 14:26
I can NOT confirm this issue as fixed with 1.1.2 as downloaded via CKAN - the sides of the OKTO probe core and the 2.5m service bay are still crooked.

**Comment by ChrisAdderley** [comment] 2020-06-18 15:48
Can you be more specific, because this is what I see:

![screenshot213](https://user-images.githubusercontent.com/5642064/85042434-0e0d5700-b140-11ea-88ab-5101219c401e.png)
![screenshot232](https://user-images.githubusercontent.com/5642064/85042697-5c225a80-b140-11ea-92e2-4df8803e9157.png)


Also to be fair to us, you are saying the 2.5m service bay in your comment, but the initial report mentions the 1.25m one...

**Comment by Vladimir-csp** [comment] 2020-07-06 08:47
I can confirm that it is slanted on some parts of the surfaces. I can wiggle a part a bit while attaching it to OKTO to find a non-slanted spot.

**Comment by ChrisAdderley** [comment] 2020-08-02 18:41
Closing in favour of #886 to put all these issues in the same place.

**Closed by ChrisAdderley** 2020-08-02 18:41 UTC
Labels: bug, question
