### ISSUE TITLE
mainsail - lower part of actuators needs rotating by 90 degrees

### ISSUE THREAD

**Issue by riocrokite** [PorktoberRevolution/ReStocked#134] opened 2019-01-11 23:35 UTC
![image](https://user-images.githubusercontent.com/9766897/51064813-e6889580-1601-11e9-9f6d-22f1fe743aa6.png)

**Comment by ChrisAdderley** [comment] 2019-01-11 23:49
Duplicate of #131

**Closed by ChrisAdderley** 2019-01-11 23:49 UTC
Labels: wontfix
