### ISSUE TITLE
Bizarre Drag Characteristics for Certain Engines using FAR

### ISSUE THREAD

**Issue by HSJasperism** [PorktoberRevolution/ReStocked#537] opened 2019-03-08 14:52 UTC
Several engines have bizarre drag characteristics, that become more noticeable with FAR installed. Engines like the Reliant, Valiant, Swivel, and Skipper work perfectly fine, but most 2.5m engines and the Mammoth are not OK inside atmospheres.

It doesn't end with the VAB. Some, like the Boar, won't allow you to go above 150m/s below 25km in Kerbin. Some others just handle badly.

Related Information:
https://forum.kerbalspaceprogram.com/index.php?/topic/182679-161-restock-revamping-ksps-art/&do=findComment&comment=3554198

https://forum.kerbalspaceprogram.com/index.php?/topic/182679-161-restock-revamping-ksps-art/&do=findComment&comment=3554204

**Comment by drewcassidy** [comment] 2019-03-08 15:08
FAR calculates drag for parts completely different from the stock game. Are you sure this happens without FAR?

**Comment by drewcassidy** [comment] 2019-03-08 15:53
It appears FAR has issues calculating drag for any parts using skinned meshes, making this at likely a FAR bug

**Comment by Zuthal** [comment] 2019-03-11 15:18
I can confirm that this issue exists for the CR-7 Rapier as well, which makes building functional spaceplanes highly annoying. It seems to be that FAR thinks the engines have a far higher cross-section than they should have.

[Example Spaceplane with Rapiers and ReStock](https://cdn.discordapp.com/attachments/132503638793912320/554680178526257162/screenshot39.png)
[Same spaceplane with Restock installed and Whiplash engine](https://cdn.discordapp.com/attachments/487573659091861506/554682214017662977/screenshot41.png)

**Comment by dkavolis** [comment] 2019-03-12 22:20
Fixed in FAR now dkavolis/Ferram-Aerospace-Research#30

**Comment by drewcassidy** [comment] 2019-03-13 05:48
If someone can quickly double check to make sure the affected parts are fixed by the latest FAR update I can close this issue

**Comment by Zuthal** [comment] 2019-03-13 13:20
The issue is fixed by the latest FAR update, yes.

**Closed** 2019-03-13 13:50 UTC
Labels: Mod Compatibility, bug
