### ISSUE TITLE
Problem with fuel tank aerodynamics

### ISSUE THREAD

**Issue by joonoro** [PorktoberRevolution/ReStocked#791] opened 2020-02-01 10:54 UTC
**Describe the bug**

Problem with FL-T800 fuel tank in Restock and with new tanks in Restock+ (at least some of the FLT-X series have the same problem). The aerodynamics model differs from vanilla and it ends up looking like in the screenshots with strange radial airflow.

I know the known issues said there's something wrong with the fuel tanks, but this bug persists even after deleting the files and revalidating cache so this makes me think it's something else.

**Screenshots**

FL-T800 behavior with Restock:

![Kerbal Space Program Screenshot 2020 02 01 - 13 09 31 28](https://user-images.githubusercontent.com/5191426/73591253-f9b02100-44f4-11ea-9f1a-b4cb4e711190.png)

FL-T800 in vanilla behavior:

![Kerbal Space Program Screenshot 2020 02 01 - 13 05 27 94](https://user-images.githubusercontent.com/5191426/73591248-eef58c00-44f4-11ea-9bdb-f76df4a0917c.png)

**List of mods installed:**
- Restock

**Comment by joonoro** [comment] 2020-02-01 10:57
Actually I think it's the winglets, I'll update this in a second after testing

**Comment by joonoro** [comment] 2020-02-01 11:20
Finished editing, take it away

**Comment by joonoro** [comment] 2020-02-01 11:38
I read in the forum thread that the aerodynamics aren't exactly the same in Restock as in vanilla, but the above doesn't strike me as intended behavior.

**Comment by ChrisAdderley** [comment] 2020-02-01 20:55
This is not aerodynamics, it's aerodynamic *effects*. Because the aero FX are generated directly off the ingame mesh, they will always be different if the model is different.

I'm not sure what can be done about this (probably nothing) but rest assured that it has no effect on gameplay.

**Comment by joonoro** [comment] 2020-02-01 20:57
Ah, thanks for the answer. It's a little annoying because it has kind of a strobe effect when it gets intense but I can live with it if it isn't messing up my aerodynamics or anything.

**Comment by ChrisAdderley** [comment] 2020-02-01 21:01
Yeah. I noticed before you edited the post something about the Skiff's effects which is a known issue: KSP 1.8 broke aero effect scaling for deforming meshes. What you were seeing is the bending pipes on the model being affected by aero and being far too large. There are some things I need to do to address this on a lot of our engine models. This is unfortunately going to be a very laborious process so I'm not really prioritizing it. 
When I do this I'll see if there are any similar issues on these fuel tanks.

**Comment by Poodmund** [comment] 2020-08-23 21:16
@ChrisAdderley is this the SkinnedMeshRenderer scale issue? If so, can this issue be closed in favour of https://github.com/PorktoberRevolution/ReStocked/issues/800?

**Comment by ChrisAdderley** [comment] 2020-08-28 16:28
This can be closed as I confirmed it's not an actual gameplay issue, and the Skiff question is actually resolved as of a version or two of restock ago.

**Closed by ChrisAdderley** 2020-08-28 16:28 UTC
