### ISSUE TITLE
HG-20 High Gain Antenna - Model issue

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#375] opened 2019-02-12 22:15 UTC
The extendable copper antenna components are sticking out further in the top to dishes. 

![image](https://user-images.githubusercontent.com/22890228/52671715-a9e5dd80-2ed0-11e9-983e-64fa1c600d3a.png)

**Comment by drewcassidy** [comment] 2019-02-12 22:34
oh dear. no the copper parts are even, the problem is the dishes are crooked. working on it

**Comment by drewcassidy** [comment] 2019-02-12 22:53
nope it was the copper. fixed with 5543da7

**Closed** 2019-02-13 00:07 UTC
Labels: art bug, restock+
