### ISSUE TITLE
LV-T30 Boattail Variant Misalignment

### ISSUE THREAD

**Issue by RyanRising** [PorktoberRevolution/ReStocked#974] opened 2021-08-14 00:32 UTC
The size or position of the model for the LV-T30 changes based on whether or not the boattail variant is selected. The nodes remain placed consistently. I did not observe any variation in the non-boattail variants, The engine bell in the white boattail seems very slightly too small (though honestly, this is barely noticeable), and the grey boattail is very obviously too long. 

This should be observable by placing the engine in the editor and cycling through its variants, but as a still image example the below screenshot should suffice to describe the problem. All engines were placed on BZ-52 Radial Attachment Points set to the same height by surface attaching to the top of the probe core and offset horizontally. 

Variant order: 1.25m (White Shroud) - Boattail (White) - Compact (White Shroud) - 1.25m (Orange/Grey Shroud) - Boattail (Orange/Grey) - Compact (Orange/Grey Shroud)

![screenshot1](https://user-images.githubusercontent.com/65933674/129429030-774a902c-8fd7-4096-9b36-5e1b6e6f9d94.png)

Mods installed:
 - Restock 1.4.2
 - ModuleManager 4.2.1
 - SquadExpansion (Breaking Ground and Making History DLCs)

Logs: I'm not sure they are relevant, but for posterity:
[KSP.log](https://github.com/PorktoberRevolution/ReStocked/files/6985669/KSP.log)

**Comment by ChrisAdderley** [comment] 2021-08-14 02:29
Working as intended

**Comment by RyanRising** [comment] 2021-08-14 02:59
> Working as intended

I know this isn’t really the place, but I’m mystified as to why that is. The stock game does not exhibit this behaviour (not that I could see, at any rate) and it’s not obvious to me at all why especially the metal boattail is so much longer than the white boattail. It visibly clips into stuff below it with that setup, and could be jarring when trying to switch paint schemes.

**Comment by ChrisAdderley** [comment] 2021-08-14 03:51
That's dev speak for 'go away I hate this mod' ;)

**Comment by RyanRising** [comment] 2021-08-14 04:54
gotcha. If it's all the same to you, I'll leave this open in the hope someone else on the project finds minor rescaling and repositioning of models a motivating activity.

**Comment by Poodmund** [comment] 2022-02-16 14:14
Resolved with https://github.com/PorktoberRevolution/ReStocked/commit/4f8eaf639e51da0778938f4eba4810bc09d21f3a

**Closed by Poodmund** 2022-02-16 14:14 UTC
Labels: art bug
