### ISSUE TITLE
Cherenkov engines have less thrust than expected when clustered

### ISSUE THREAD

**Issue by Antoine-M** [PorktoberRevolution/ReStocked#804] opened 2020-02-29 16:53 UTC
**Describe the bug**
Steps to reproduce:
 - Create a craft with a probe core, a fuel tank, and 7 Cherenkov engines *with the longer pipe facing outward* (see screenshot)
 - Cheat the craft in orbit, orient it prograde, and start the engines
 - Observe that the delta-v decreases much faster than the velocity increases OR with Kerbal Engineer installed, observe that "Horizontal acceleration" (actual change in velocity) is much lower than "Acceleration" (expected acceleration based on thrust and mass) (see screenshot).

The difference is also observed with the pipe facing inward. If facing sideways, there is still a difference but it is less dramatic.

**Screenshots**
![20200229172810_1](https://user-images.githubusercontent.com/9202694/75611547-ce344c80-5b1b-11ea-82a9-4ddc8a19393d.jpg)
![20200229172732_1](https://user-images.githubusercontent.com/9202694/75611550-d42a2d80-5b1b-11ea-9f21-63e7ea2a7d17.jpg)

**List of mods installed:**
 - Restock+
 - Kerbal Engineer Redux (optional, makes it easier to see the issue)

Tested in KSP 1.8.1

**Comment by ChrisAdderley** [comment] 2020-02-29 23:24
I'll dig into this a bit further but my initial gut feeling is that there is a little thrust loss, because:
1. Each of the outboard engines is having the thrust of one of its verniers blocked by the centre engine
2. The inboard engine is having both of its veniers blocked by the outboard engines. 

If a thrust vector is blocked in stock KSP, it produces no thrust. Currently the thrust is split with the main engine doing 96% and each vernier 2%, so this is going to cost 2% of thrust of each outboard and 4% of the centre, so maybe 2.3% overall. 

I don't have a great picture of exactly how KER calculate the quantities it does so I have to look further into this, but I suspect you wouldn't see this effect if you clustered without blocking the verniers. This is supported by your observation that the effect varies with different rotation of the pipes.
If this is all the case, it's intended behaviour.

**Comment by Antoine-M** [comment] 2020-03-02 11:40
It's a lot than a few percents of thrust loss, though, it's nearly half of it. Much more than vernier obstruction could explain.

Regarding KER, I brought it up because it makes it easier to see the difference, especially in screenshots, but like I said the issue can be observed by comparing delta-v expenditure and velocity.

**Comment by ChrisAdderley** [comment] 2020-03-02 17:53
Yep, this is why it's still an investigation. The behaviour makes sense, the magnitude does not.

**Comment by ChrisAdderley** [comment] 2020-03-11 18:06
I think it's all but confirmed that the stock feature which allows allocation of thrust between multiple locations is broken. Some tests have confirmed this, and doing the math on this particular issue seems to support it (in terms of thrust allocation to the verniers). Not entirely sure at this time what our approach will be to address this. We need to determine what KSP version it broke in first, I suppose.

**Comment by Poodmund** [comment] 2020-04-22 20:31
![Untitled-1](https://user-images.githubusercontent.com/10106634/80030121-af30b600-84df-11ea-9a0f-882be93557ca.png)

I just put this craft into a high alt/low accel orbit and increased my velocity by 1km/s and the dV expended was about 1005m/s give or take a couple m/s. The thrust readout in KER read 1800kN which seems correct for full thrust for 6 of the engines.

The only thing was the craft could only use the upper thrusters to roll counter-clockwise and not clockwise. Maybe that is due to thrust transform occlusion? *shurg*

**Comment by ChrisAdderley** [comment] 2020-04-22 20:37
I did a bunch of tests and I think the issue is now resolved.

**Comment by Poodmund** [comment] 2020-04-22 20:51
I'd be happy, with the craft above with its vernier thrusters located so close together, that there was no significant loss of thrust as previously indicated. I'll close this but @Antoine-M please re-open with more details if you find an issue.

**Closed by Poodmund** 2020-04-22 20:51 UTC
Labels: question
