### ISSUE TITLE
Illuminator Mk1 and Mk2 always on, no texture change

### ISSUE THREAD

**Issue by tybot3k** [PorktoberRevolution/ReStocked#522] opened 2019-03-06 21:22 UTC
Both Illuminator's Mk1 and 2 display as always being on, both in VAB and in space. Toggling them off stops power usage but light still persists. Also the part textures themselves show as if they're always off; the "bulbs" are always dark.

**Comment by ChrisAdderley** [comment] 2019-03-06 21:34
Can't reproduce this - do you have some other mod that conflicts?

![screenshot193](https://user-images.githubusercontent.com/5642064/53915305-836d1b00-4014-11e9-94d2-7d9bd28b73d4.png)
![screenshot194](https://user-images.githubusercontent.com/5642064/53915308-836d1b00-4014-11e9-9e80-ef24ac991c78.png)

**Comment by tybot3k** [comment] 2019-03-06 22:21
It's not a clean install, so there very well could be a conflict that's at fault. I'll have to do significant digging to narrow down which is the culprit though. I will note that modded lights seem to operate fine, it's just the stock ones.

**Comment by ihsoft** [comment] 2019-03-07 05:38
@tybot3k By a chance, are you using SurafceLights mod?

**Comment by drewcassidy** [comment] 2019-03-07 05:38
Do you have Surface Lights installed by any chance? https://github.com/ihsoft/SurfaceLights/issues/19

**Comment by tybot3k** [comment] 2019-03-07 15:57
@ihsoft I do in fact. If you suspect that being the culprit I can test it out on my local setup tonight.

**Comment by ChrisAdderley** [comment] 2019-03-07 16:18
If you confirm it, close this and see progress here: https://github.com/PorktoberRevolution/ReStocked/issues/532

**Comment by ihsoft** [comment] 2019-03-08 06:08
@tybot3k If you have SL installed, than what you observe is https://github.com/ihsoft/SurfaceLights/issues/19. The problem is investigated and the fix on its way.

**Closed** 2019-03-08 06:45 UTC
Labels: CNR, bug, restock base
