### ISSUE TITLE
Reflective shader behaves strangely in cases of zero ambient light

### ISSUE THREAD

**Issue by GregroxMun** [PorktoberRevolution/ReStocked#523] opened 2019-03-07 00:44 UTC
![https://i.imgur.com/vx1bAC7.png](https://i.imgur.com/vx1bAC7.png)

![https://i.imgur.com/9f2pbtD.png](https://i.imgur.com/9f2pbtD.png)

The casing for each solar panel cell (not the box they're stored in, but the gray metal thing holding them together) is black when in flight. It does handle specular reflection of light, but it should be light gray and instead appears dark black.

example of slight environmental reflection from some angles:

![https://i.imgur.com/lkVAzWe.png](https://i.imgur.com/lkVAzWe.png)

![https://i.imgur.com/ae9x7jM.png](https://i.imgur.com/ae9x7jM.png)

When I turn ambient lighting up (which should not be necessary as this is an extremely visually unappealing result especially in space) the gray casings reappear.

![https://i.imgur.com/zRZbfG0.png](https://i.imgur.com/zRZbfG0.png)

+7% ambient lighting

![https://i.imgur.com/HxuboFX.png](https://i.imgur.com/HxuboFX.png)

-30% ambient lighting

I noticed this in the pre-release version, I wish I had reported it before release.

At slower ambient light levels, the panel casings DO reflect sunlight, their brightness when lit by sun is higher than when in darkness. But their sunlit brightness seems to be multiplied by the ambient light setting.

While this can be "fixed" by using the default ambient light levels, this results in an undesirable visual appearance in the game, particularly in space. I never liked ambient lighting and I'm sure I'm not the only one. (It's also worth noting that people who play with ambient lighting turned up beyond the default for visibility reasons will have their solar panel casings rendered too bright as well)

**Comment by drewcassidy** [comment] 2019-03-07 02:01
The specular maps are black everywhere the frame is. Assigning this to Nertea who is responsible for the specular map for those parts

**Comment by ChrisAdderley** [comment] 2019-03-07 03:14
Can't repro, from latest master:

![screenshot195](https://user-images.githubusercontent.com/5642064/53929846-fcd03200-4043-11e9-8c5f-c9595d532639.png)
Clearly shows grey casings...

**Comment by GregroxMun** [comment] 2019-03-07 14:04
It might be related to PlanetShine or Kopernicus (both involve light sources, though I can't think of a way in which they'd affect this), I'll try removing them and seeing if the issue disappears.

**Comment by GregroxMun** [comment] 2019-03-07 14:16
Here are screenshots with +12%:

![https://i.imgur.com/sloWpU6.png](https://i.imgur.com/sloWpU6.png)

and -100% ambient lighting:

![https://i.imgur.com/Ai8L6qa.png](https://i.imgur.com/Ai8L6qa.png)

With nothing except for ReStock, ReStockPlus, Squad, SquadExpansion, and ModuleManager.4.0.2. This is still the 0.1.0 version. I'm about to download and test the 0.1.1 version.

**Comment by GregroxMun** [comment] 2019-03-07 14:29
I can verify I experience the same bug with the current master version.

**Comment by drewcassidy** [comment] 2019-03-07 14:32
Kopernicus also replaces the deployable solar panel module with its own, that could have something to do with this

**Comment by GregroxMun** [comment] 2019-03-07 14:34
> Kopernicus also replaces the deployable solar panel module with its own, that could have something to do with this

It might if it weren't for the fact that this also happens in a completely new save that's only ever had ReStock solar panels and never had Kopernicus installed with it.

**Comment by ChrisAdderley** [comment] 2019-03-07 16:15
I still can't reproduce it in my barebones (MM, RS, RS+) install, until I can I have no ability to fix it. 

Are you using a fresh Restock GameData? If you are upgrading things from an old test version, there may be tga textures left over that are not loading correctly.

**Comment by drewcassidy** [comment] 2019-03-07 17:33
Do you have any unusual graphics settings (using DX11 or something)? Do you see the same thing on any other part using the PBR shader introduces in 1.5?

**Comment by GregroxMun** [comment] 2019-03-08 01:10
As far as I know, my graphics settings are normal, and I don't see problems on other PBR parts (except the other solar panels)

**Comment by drewcassidy** [comment] 2019-03-08 19:26
Honestly this is starting to look like a stock/Unity bug to me. I can send you a test part to see what exactly is going on (I think the diffuse map isnt being used correctly in the lighting step of the shader on your machine for whatever reason)
a few more questions
- does it look dark in the VAB?
- what do the backsides of the panels look like?
- what happens if you point a spotlight at them?

**Comment by Poodmund** [comment] 2019-03-09 14:44
I cannot reproduce this either. Vanilla 1.6.1 install with MH, MM, ReStock and RS+ running on DX9:

![Untitled-1](https://user-images.githubusercontent.com/10106634/54072983-99c7e080-4279-11e9-9b4b-da79c9459e75.png)

![Untitled-2](https://user-images.githubusercontent.com/10106634/54072985-9af90d80-4279-11e9-88cd-24a108a0f212.png)

As an addendum I also do not get this issue on a modded install using the same graphical settings with Scatterer, EVE, Planetshine and DOE of which may have had an effect.

**Comment by GregroxMun** [comment] 2019-03-11 00:53
You're right, the title is misleading. However, I did explicitly say in the main post that they were black when ambient lighting was turned to -100%.

Can @ChrisAdderley and @drewcassidy verify that they turned ambient lighting down to -100% when they could not replicate? Or were you using default ambient lighting? (Which is fine for the panels, but looks bad as I explained in the original post)

**Comment by ChrisAdderley** [comment] 2019-03-11 05:14
I did not test at that low an ambient light level as it was not at all clear in the post. As the default settings have lighting, saying that the light is "raised" at that point is not very helpful.
I've edited the title to be informative.

**Comment by drewcassidy** [comment] 2019-03-13 02:55
I suggest you report this as a bug with the squad bug tracker. There is something weird going on with that shader that I can’t even reproduce with the version that ships with PartTools. You could also try using the material replacer module included in the restock DLL to replace the shader with Bumped Specular, which loses the reflectivity but wouldn’t be completely dark without ambient light

**Comment by ChrisAdderley** [comment] 2019-10-28 21:00
In case anyone was curious, 1.8 did not resolve this!

**Comment by drewcassidy** [comment] 2020-02-12 21:23
Did you ever report this on the Squad bug tracker? I have a hunch the cause is also what makes parts look different between the VAB and in flight

**Comment by Porkjet** [comment] 2020-05-10 02:50
The only thing bugged about this is the stock Ambient light slider itself.
It looks like to me that the slider is not only boosting the classical ambient light but also the reflection probe derived ambient light that PBR shaders use, which is a bad idea.

Why this is showing up on the RS solar panel in particular with ambient boost 0 is that it has areas with 0 reflectivity, so it doesn't show a specular highlight either and goes completely black.
The stock reflective parts seem to have some reflectivity value all over so while they go unnaturally dark too, they still have the spec highlight.

I have to say tho that I don't understand why anyone would want to set the Ambient Light Boost to -100 to begin with. The entire game looks like a bug with this. If it's concern about ambient light in space, that seems to be at exactly 0 now if the slider is set to 0. Just leave that slider at 0.

If you want ambient light manipulation done the proper way, planet shine does a good job there.

**Closed** 2020-08-28 16:29 UTC
Labels: CNR, Stock Bug, art bug, restock base, wontfix
