### ISSUE TITLE
New Skipper normal bug and UV wavyness

### ISSUE THREAD

**Issue by Rodg88** [PorktoberRevolution/ReStocked#846] opened 2020-04-26 09:48 UTC
![screenshot793](https://user-images.githubusercontent.com/2611674/80303891-566e5f80-87f6-11ea-8d2d-38b8b5139e51.png)
Normal bug in the red circle, and the middle section of the nozzle (in the blue section) has a wavy distorted texture.

**Comment by Porkjet** [comment] 2020-04-26 10:52
The wavy texture is a side effect of triangulation of taper-stretched UV rectangles. In this case tapered polygons UV's were stretched into perfect right angled squares to be able to use a straight strip of texture piping, which is often easier to produce and straight pixel alignment makes it look really nice and crisp.
The problem is that when UV's get deformed, they don't taper-deform the texture nicely, they can only sort of, parallel distort pixels, which causes this tear/distortion between triangles. There's no remedy for this, it can only be reduced by adding support loops. Which it looks to me was done a lot here already to kinda even it out as much as possible.

IMO It's not so bad on this model that I would worry about it at all. You can only really notice it by zooming in crazy close.

**Comment by ChrisAdderley** [comment] 2020-04-26 20:52
Adjusted in latest commit

**Comment by Poodmund** [comment] 2020-04-26 21:33
Area under pipe fixed for me with https://github.com/PorktoberRevolution/ReStocked/commit/7cdb73d0a35fd310874cacd45c6f5f19cb99933e and wavy texture issue is as Porkjet explained above. Not noticeable unless you really look closely. The whole engine bell texture covers a region of 565x207 pixels which is tiny so the result is pretty damn good with respect to that. 😄

**Comment by Poodmund** [comment] 2020-04-29 21:23
![Untitled-1](https://user-images.githubusercontent.com/10106634/80648343-ef57e180-8a67-11ea-8c28-a3d9b8980366.png)

I think this commit (https://github.com/PorktoberRevolution/ReStocked/commit/7cdb73d0a35fd310874cacd45c6f5f19cb99933e) unfortunately introduced a graphical bug inside the engine bell making a black streak run North to South. Here is a screenshot of the old v1 Skipper on the left and the v2 Skipper on the right.

**Comment by ChrisAdderley** [comment] 2020-04-29 22:06
Done in latest commit

**Comment by Poodmund** [comment] 2020-04-30 09:00
Above issue resolved with https://github.com/PorktoberRevolution/ReStocked/commit/b5abd22b3c080c27b0612605eca416b9d16a4f7a

**Closed by Poodmund** 2020-04-30 09:00 UTC
Labels: art bug, restock base
