### ISSUE TITLE
Swivel engine attaches far away

### ISSUE THREAD

**Issue by lordcirth** [PorktoberRevolution/ReStocked#545] opened 2019-03-10 23:59 UTC
When attaching the Swivel engine, it attaches way below where it should:

https://i.imgur.com/xCKa0pm.png

I also noticed that I have 2 LV-T15's.
Mod list:

```
000_ClickThroughBlocker
001_ToolbarControl
AllYAll
B9PartSwitch
CommunityCategoryKit
CommunityResourcePack
CommunityTechTree
ContractConfigurator
CryoEngines
CryoTanks
DeployableEngines
DiscordRP
DistantObject
DMagicOrbitalScience
DynamicBatteryStorage
FinalFrontier.dat
KerbalAtomics
KerbalEngineer
Kerbalism
Kopernicus
kOS
MemGraph
ModularFlightIntegrator
ModuleManager.4.0.2.dll
NavBallDockingAlignmentIndicatorCE
NearFutureConstruction
NearFutureElectrical
NearFutureLaunchVehicles
NearFutureProps
NearFuturePropulsion
NearFutureSolar
NearFutureSpacecraft
Nereid
NRAP
PreciseEditor
ProbesBeforeCrew
RCSBuildAid
ReStock
ReStockPlus
RLA_Reborn
ScienceAlert
ScienceParamModifier
Sigma
Squad
SquadExpansion
StationPartsExpansion
Trajectories
TriggerTech
UniversalStorage2
[x] Science!
```

**Comment by drewcassidy** [comment] 2019-03-11 00:44
Could not reproduce, are you sure you have the mod installed correctly? You shouldn't be seeing two LV-T15s either
<img width="1136" alt="Screen Shot 2019-03-10 at 5 43 57 PM" src="https://user-images.githubusercontent.com/3837797/54094177-17641d00-435c-11e9-890e-1b51d14bd937.png">

**Comment by lordcirth** [comment] 2019-03-11 13:16
Tried an install with only Restock and it didn't reproduce. I will try bisecting later.

**Comment by ChrisAdderley** [comment] 2019-03-13 17:59
Ok, going to close this the. Re-open if you find an issue for us.

**Closed by ChrisAdderley** 2019-03-13 17:59 UTC
Labels: CNR, bug, restock base

**Comment by lordcirth** [comment] 2019-03-14 01:54
I uninstalled and reinstalled Restock and Restock+ through CKAN and now it's fine. Weird but ok.
