### ISSUE TITLE
Real Chute + Restock + !FAR is not compatible - high drag on parachutes.

### ISSUE THREAD

**Issue by CovertGuardian** [PorktoberRevolution/ReStocked#756] opened 2019-11-14 01:35 UTC
Chutes end up have massive drag, even though they will open.

Problem seems to be RealChute removes Module{Parachute] so Restock cannot update
that module - but Restock still adds large drag cube entry even with no Module[Parachute] to
control which element of drag cube is used.

Suggested fix is to only add large Drag cube if RealChute is not present.

Test fix locally.
Adding drag cube condition "DRAG_CUBE:NEEDS[!RealChute]" to the chutes in GameData\ReStock\Patches\Utility\restock-parachutes.cfg seems to fix the issue.

**Comment by CovertGuardian** [comment] 2019-11-14 02:45
Looking harder -- You have a compatibility patch.  Problem is timing.
Patches apply in order: RealChute, Compatibility Patch and then Restock.
Restock adds the drag cube back after the compatibility patch removed it.

Changing the AFTER clause in RealChute.cfg compatibility patch also fixes the problem
and seems more like the intended approach (AFTER Restock instead of AFTER RealChute)

**Comment by ChrisAdderley** [comment] 2019-11-16 13:54
Same root cause as #751.

**Comment by ChrisAdderley** [comment] 2019-11-16 14:10
I believe it should be fixed with 63fb192045892cc64d42d629e5fef1fd61c31cf0. Let me know if possible.

**Comment by CovertGuardian** [comment] 2019-11-16 15:56
My configuration with RealChute works fine with the update RealChute.cfg

Not sure if it is an issue or not but in FAR.cfg one of the chutes is
marked :NEEDS[FerramAerospaceResearch]:AFTER[ReStock] while the others are marked
:AFTER[FerramAerospaceResearch].  I don't understand what is going on with Ferram well enough
to know if that is intentional or an issue.

At least as far as my issue the new config is good.

**Comment by ChrisAdderley** [comment] 2019-11-17 02:44
Sounds good!

**Closed** 2019-11-30 21:16 UTC
Labels: Mod Compatibility, duplicate
