### ISSUE TITLE
weird attachment behavior

### ISSUE THREAD

**Issue by MuchozolF** [PorktoberRevolution/ReStocked#551] opened 2019-03-12 21:02 UTC
![21-32-35](https://user-images.githubusercontent.com/48312586/54235058-b6ca1100-4510-11e9-9a5f-2d410216734e.jpg)

For some reason, after detaching this fuel tank from one of my crafts the regular attachment nodes on the tank and on the probe core have disappeared. When I tried putting the tank down, it attached like this (see screenshot). Afterward, I was able to pick up the whole vessel, just by clicking on the ghostly fuel tank and attaching parts to the top. I was unable to detach the fuel tank, without saving the vessel and reloading it.

I wasn't able to reproduce this bug after relaunching the game. I assume it's a stock bug, I really don't know how this stuff works though.

**Comment by drewcassidy** [comment] 2019-03-12 21:05
Oh nice this bug is back... 

I’ve encountered this exact issue several years ago. As far as I can tell it’s a stock bug, and one I’ve never been able to reliably reproduce

**Comment by drewcassidy** [comment] 2019-03-12 21:08
I’m going to close this issue since I’m confident it’s a stock bug. If you can reproduce it again and show its restock related feel free to reopen it

**Comment by blowfishpro** [comment] 2019-03-12 21:08
If you do reproduce, be sure to get logs, they might give some indication as to what's going on

**Closed** 2019-03-12 21:08 UTC

**Comment by MuchozolF** [comment] 2019-03-12 21:19
Logs? Is that the text file, in the game directory, named "KSP"?

**Comment by blowfishpro** [comment] 2019-03-12 22:23
`KSP.log` in the game directory, yes

**Comment by theonegalen** [comment] 2019-03-14 03:30
I ran across the same thing using the 0.625 meter fairing base a couple of weeks ago. If it happens again I'll make sure to upload a log.
