### ISSUE TITLE
KR-1 Boar - Shroud Issue

### ISSUE THREAD

**Issue by TykoTek** [PorktoberRevolution/ReStocked#275] opened 2019-02-02 23:18 UTC
Shroud is slightly over 2.5m in diameter. Picture shows bottom so I could zoom in, but this width is too big at the top as well

![image](https://user-images.githubusercontent.com/22890228/52170371-af3b6f00-26fd-11e9-8ad3-4cc4bb0c5dd8.png)

**Comment by ChrisAdderley** [comment] 2019-02-07 07:40
Scaled down in 6c6dba1

**Comment by TykoTek** [comment] 2019-02-07 15:02
Fixed

**Comment by Poodmund** [comment] 2019-02-09 22:04
Possibly some regression? I'm using https://github.com/PorktoberRevolution/ReStocked/commit/a55c6a48f0dfbdf512bbc36a5a5711597b790904 and experiencing a few issues here:

The 2.5m shroud has a part extending too far up, into the part above it on one side of the shroud:

![untitled-1](https://user-images.githubusercontent.com/10106634/52526798-76c80200-2cb6-11e9-8ce8-93fd0eb41d06.png)

And the Compact variant shroud seems to be of a larger diameter that 2.5m and it located too far up into the part attached above it (compare the two screenshots):

![untitled-2](https://user-images.githubusercontent.com/10106634/52526802-8b0bff00-2cb6-11e9-87a4-f03c9309eb12.png)

It might be that the shroud for both is too tall for the part?

**Comment by ChrisAdderley** [comment] 2019-02-09 22:29
Compact was never reported. 2.5m looks fine to me.

**Comment by ChrisAdderley** [comment] 2019-02-09 22:33
compact adjusted in e10b094

**Comment by TykoTek** [comment] 2019-02-09 23:06
This is the compact variant and the shroud is just over 2.5m in diameter you can see it overhangs the decouplers on both top and bottom

![image](https://user-images.githubusercontent.com/22890228/52527343-0ef4c580-2c7c-11e9-93a2-a11ee1f53cd5.png)

![image](https://user-images.githubusercontent.com/22890228/52527345-1b791e00-2c7c-11e9-9d8a-dffbe026292b.png)

**Comment by Poodmund** [comment] 2019-02-10 10:05
Heights all seem fine now. As Tyko suggests above, the Compact shroud is slightly wider than the stack diameter. Here's a little .gif to judge the difference:

![untitled-1](https://user-images.githubusercontent.com/10106634/52532343-6dbd4c00-2d1b-11e9-8de3-bc50a8059a36.gif)

**Comment by ChrisAdderley** [comment] 2019-02-10 21:02
Fixed in f950fea

**Comment by Poodmund** [comment] 2019-02-10 21:38
Resolved in https://github.com/PorktoberRevolution/ReStocked/commit/f950feaabac4da21a1121b605846d191de46598e

**Closed by Poodmund** 2019-02-10 21:38 UTC
Labels: art bug, restock+
